apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
spec:
  vault:
    name: dyma-azure-vault
    object:
      name: MYSQL-ROOT-PASSWORD # nom du secret sur azure
      type: secret # type sur azure (secret, key ou certificat)
  output: 
    secret: 
      name: mysql-secret # nom du secret sur k8s
      dataKey: MYSQL_ROOT_PASSWORD # nom de la clé du secret sur k8s